from tkinter import *
window = Tk()
window.config(bg = 'light blue')
window.title('Calculator')
def myclick(exp):
  se.insert(END, exp)
def clear():
  se.delete(0,END)
def evaluate():
  exp = se.get()
  result = eval(exp)
  se.delete(0, END)
  se.insert(END, result)
se = Entry(window, bg = 'light pink', width= 15, font = ('Arial', 20, 'bold'))
se.grid(row=1,column=1, columnspan=3)
b1 = Button(window, text = '1',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(1))
b1.grid(row=2, column=1)
b2 = Button(window, text = '2',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(2))
b2.grid(row=2,column=2)
b3 = Button(window, text = '3',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(3))
b3.grid(row=2, column=3)
b4 = Button(window, text = '4',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(4))
b4.grid(row=3, column=1)
b5 = Button(window, text = '5',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(5))
b5.grid(row = 3, column=2)
b6 = Button(window, text = '6',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(6))
b6.grid(row = 3, column=3)
b7 = Button(window, text = '7',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(7))
b7.grid(row = 4, column=1)
b8 = Button(window, text = '8',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(8))
b8.grid(row = 4, column=2)
b9 = Button(window, text = '9',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(9))
b9.grid(row = 4, column=3)
b0 = Button(window, text = '0',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick(0))
b0.grid(row = 5, column=2)
bplus = Button(window, text = '+',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick('+'))
bplus.grid(row = 6, column=1)
bminus = Button(window, text = '-',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick('-'))
bminus.grid(row = 6, column=2)
bmulti = Button(window, text = '*',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick('*'))
bmulti.grid(row = 6, column=3)
bdiv = Button(window, text = '/',font = ('Arial', 20, 'bold'), width=2, command= lambda:myclick('/'))
bdiv.grid(row = 7, column=1)
bclear = Button(window, text = 'CLEAR',font = ('Arial', 20, 'bold'), width=5, command= clear)
bclear.grid(row = 7, column=2, columnspan=2)
bequal = Button(window, text = '=',font = ('Arial', 20, 'bold'),width=5, command= evaluate)
bequal.grid(row = 8, column=1,columnspan=3)
window.mainloop()