from tkinter import *

window = Tk()
window.title('Menu bar example')
window.geometry("200x300")
menubar = Menu(window, bg = 'orange', fg = 'black', activebackground= 'white', activeforeground='black')
file = Menu(menubar, tearoff=0, bg = 'orange', fg = 'black')
file.add_command(label= "New")
file.add_command(label='Open')
file.add_command(label='Save')
file.add_command(label='Save as')
file.add_separator()
file.add_command(label= 'Exit', command=window.quit)
menubar.add_cascade(label= "File", menu= file)
edit = Menu(menubar, tearoff=0, bg = 'green', fg='black')
edit.add_command(label= 'Cut')
edit.add_command(label='Copy')
edit.add_command(label = 'Paste')
edit.add_separator()
edit.add_command(label='Undo')
edit.add_command(label='Redo')
edit.add_separator()
edit.add_command(label= "Find")
edit.add_command(label='Replace')
menubar.add_cascade(label= 'Edit', menu=edit)
help = Menu(menubar, bg='purple', fg='black')
help.add_command(label= 'Welcome')
help.add_command(label='Show all commands')
help.add_command(label='Documentation')
help.add_separator()
help.add_command(label='About')
help.add_command(label= 'Keyboard shortcut references')
help.add_command(label= 'Tips and Tricks')
help.add_command(label='Video Tutorials')
menubar.add_cascade(label= 'Help', menu=file)
window.config(menu = menubar)
window.mainloop()