from tkinter import *
import time
from datetime import datetime
window = Tk()
window.geometry('800x800')
window.title('Resturant Manegment System')
fr = Frame(window)
fr.pack()
l1 = Label(fr, text='Resturant Manegment System',font = ('Arial',30, 'bold'),fg = '#47bbde')
l1.grid(row=1, column=1, columnspan=4)
def update():
  t = datetime.now()
  t = t.strftime('%a %b %d %H:%M:%S %Y')
  ti.config(text = t)
  ti.after(1000, update)
ti = Label(fr, text= '',font = ('Arial',20), fg= '#47bbde')
ti.grid(row=2, column=1, columnspan=4)
onl = Label(fr, text='Order No.', fg = '#47bbde' , font= ('Arial', 20))
onl.grid(row=3, column=1, pady = 10)
one = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
one.grid(row=3, column=2, pady = 10)
dl = Label(fr, fg = '#47bbde', text='Drinks', font= ('Arial', 20), width= 13)
dl.grid(row = 3, column=3, pady = 10)
de = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
de.grid(row =3, column=4, pady = 10)
fll = Label(fr, text='Fries Meal', fg = '#47bbde' , font= ('Arial', 20))
fll.grid(row=4, column=1, pady = 10)
fle = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
fle.grid(row=4, column=2, pady = 10)
cl = Label(fr, fg = '#47bbde', text='cost', font= ('Arial', 20), width= 13)
cl.grid(row = 4, column=3, pady = 10)
ce = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
ce.grid(row =4, column=4, pady = 10)
lml = Label(fr, text='Lunch Meal', fg = '#47bbde' , font= ('Arial', 20))
lml.grid(row=5, column=1, pady = 10)
lme = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
lme.grid(row=5, column=2,pady=10)
bml = Label(fr, fg = '#47bbde', text='Burger Meal', font= ('Arial', 20), width= 13)
bml.grid(row = 6, column=1, pady = 10)
bme = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
bme.grid(row =6, column=2, pady = 10)
txl = Label(fr, fg = '#47bbde', text='Tax', font= ('Arial', 20), width= 13)
txl.grid(row = 6, column=3, pady = 10)
txe = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
txe.grid(row =6, column=4, pady = 10)
pzl = Label(fr, fg = '#47bbde', text='Pizza Meal', font= ('Arial', 20), width= 13)
pzl.grid(row = 7, column=1, pady = 10)
pze = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
pze.grid(row =7, column=2, pady = 10)
cbl = Label(fr, fg = '#47bbde', text='Cheese Burger', font= ('Arial', 20), width= 13)
cbl.grid(row = 8, column=1, pady = 10)
cbe = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
cbe.grid(row =8, column=2, pady = 10)
totl = Label(fr, fg = '#47bbde', text='Total', font= ('Arial', 20), width= 13)
totl.grid(row = 8, column=3, pady = 10)
tote = Entry(fr, bg = '#47bbde', fg = 'black',  font= ('Arial', 20), width= 13)
tote.grid(row =8, column=4, pady = 10)
prib = Button(fr, text='PRICE', fg = 'black',bg = 'green', bd =10, width=8, font= ('arial',18, 'bold'))
prib.grid(row=9, column=1, pady=10)
totb = Button(fr, text='TOTAL', fg = 'black',bg = 'blue', bd =10, width=8, font= ('arial',18, 'bold'))
totb.grid(row=9, column=2, pady=10)
resb = Button(fr, text='RESET', fg = 'black',bg = 'purple', bd =10, width=8, font= ('arial',18, 'bold'))
resb.grid(row=9, column=3, pady=10)
exb = Button(fr, text='EXIT', fg = 'black',bg = 'red', bd =10, width=8, font= ('arial',18, 'bold'))
exb.grid(row=9, column=4, pady=10)
update()
window.mainloop()